version: '{build}'

skip_tags: true
skip_commits:
  message: /\[ci skip\]/

clone_depth: 10

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "10"
  ASCIIDOCTOR_CORE_VERSION: "master"

install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version
  - cd packages/core
  - npm ci

build_script:
- node tasks/build.js
- node tasks/test/unsupported-features.js
- npm run test:node
- npm run test:browser
- npm run examples

test: off
